### PR TITLE
Add DOS error codes enum

### PR DESCRIPTION
**Pull request by thomasarmel**

### CODE REVIEW

**Comment by RandomInsano** [comment]
Hi! I've been mostly lurking but should the `from_u8()` function just return UnknownError? DOS didn't have Option<> so that's what that value is designed for.

**Comment by RandomInsano** [comment]
Ah, also for ergonomics does it make sense to implement these with From/Into traits?
https://doc.rust-lang.org/rust-by-example/conversion/from_into.html

**Comment by thomasarmel** [comment]
Hi,
Yes of course it's better to implement From/Into traits, my bad 😄 
I will amend the PR

About the `Option` and `UnknownError`: I'm no expert in Rust but I understand that the philosophy of the language is to ask the programmer to deal with every possible error or case. Returning `UnknownError` would instead confront it with an arbitrary choice. In this case I think it's better to implement the `TryFrom` trait, and the programmer can then turn it into `UnknownError` if he wishes.

**Comment by thomasarmel** [comment]
@o8vm

**Comment by o8vm** [comment]
thanks!!!

**Pull request merged**
